import os

os.environ["SENDGRID_API_KEY"]="YOUR_SENDGRID_API_KEY"
os.environ["EMAIL_FROM"]="EMAIL_FROM"
os.environ["HASH"]="YOUR_HASH"
os.environ["TWILIO_ACCOUNT_SID"]="YOUR_TWILIO_ACCOUNT_SID"
os.environ["TWILIO_AUTH_TOKEN"]="YOUR_TWILIO_AUTH_TOKEN"
os.environ["TWILIO_PHONE_NUMBER"]="YOUR_PHONE_NUMBER"
